### ISSUE TITLE
Please guide me how to run on my local device ?

### ISSUE THREAD

**Issue by Khemendra-Bhardwaj** [kristinajoks/ytsentiment#1]

**Comment by obfuscated-loop** [comment]
@Khemendra-Bhardwaj It is a Visual Studio solution, you can [download Visual Studio here](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&channel=Release&version=VS2022&source=VSLandingPage&passive=false). Then open up the `18203Proj3.sln` file and you'll see the project code. You can then run it under debug mode by pressing `F5` within Visual Studio.
